apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{ .Values.IMAGE_NAME }}
        ports: 
        - containerPort: 8000
          
